<?php

/**
 * @file
 * Contains special field
 *
 */

use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;

/*
 * Implements hook_form_alter
 */
function special_field_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_repertoiredesformationsaunumeriq_form':
      $form['#attached']['library'][] = 'portailcrsn/special_field';
      $options = $form['field_metier_s_cible_s_']['widget']['#options'];

      $childs = field_metier_cible($options);

      $form['field_metier_s_cible_s_']['widget']['#options'] = $childs;
      break;
    case 'node_repertoiredesformationsaunumeriq_edit_form':
      $form['#attached']['library'][] = 'portailcrsn/special_field';
      $options = $form['field_metier_s_cible_s_']['widget']['#options'];

      $childs = field_metier_cible($options);

      $form['field_metier_s_cible_s_']['widget']['#options'] = $childs;
      break;
  }
}

/*
 * Used to seperate parent for child
 */
function field_metier_cible($options) {
  foreach ($options as $key => $option) {
    if(!preg_match('/^-/', $option)){
      $parent = $option;
    }
    else{
      $childs[$parent][$key] = preg_replace('/-/', ' ', $option);
    }
  }
  return $childs;
}

