module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  backup_migrate: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_update: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  devel_node_access: 0
  disable_messages: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  entity: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_group_migrate: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  kint: 0
  language: 0
  link: 0
  locale: 0
  mailsystem: 0
  menu_block: 0
  menu_per_role: 0
  menu_ui: 0
  nocurrent_pass: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  reroute_email: 0
  search: 0
  shortcut: 0
  simple_mail: 0
  stage_file_proxy: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  toolbar_menu: 0
  tour: 0
  twig_field_value: 0
  update: 0
  user: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  portailcrsn: 0
  bactency: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: fr
