include_home_segment: 1
home_segment_title: Home
include_title_segment: 0
_core:
  default_config_hash: 2QHDzZ5MXwIpnHFjGDKpIt7m2EajgfUHCdaARcxRg2M
langcode: fr
include_invalid_paths: 1
excluded_paths: ''
segments_separator: null
title_segment_as_link: 0
title_from_page_when_available: 0
