favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'https://grand-est.numeric-emploi.org/themes/portailcrsn/favicon.ico'
  use_default: 1
schema: '8000'
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: themes/portailcrsn/logo.svg
  url: ''
  use_default: 1
schemas:
  bootstrap: 8000
  portailcrsn: 8000
forms_smart_descriptions: 0
region_wells:
  menu_user_role: ''
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
modal_enabled: 0
langcode: fr
