menus:
  account:
    active: false
    weight: 0
  menu-gestionnaire:
    active: false
    weight: 1
  gestion-des-formations:
    active: false
    weight: 2
  informations:
    active: false
    weight: 3
  te:
    active: false
    weight: 4
  formation:
    active: false
    weight: 5
  main:
    active: false
    weight: 7
  menu-presentation-de-l-asso:
    active: false
    weight: 8
  tools:
    active: false
    weight: 9
